pub const FIGHTER_KIRBY_GENERATE_ARTICLE_FIREBALL: i32 = 40;
pub const FIGHTER_KIRBY_GENERATE_ARTICLE_EXPLOSIVEFLAME: i32 = 41;
pub const FIGHTER_KIRBY_GENERATE_ARTICLE_EXPLOSIVEFLAME_RESERVE: i32 = 42;
pub const FIGHTER_KIRBY_GENERATE_ARTICLE_REFLECTIONBOARD: i32 = 43;
